# @package _group_
name: vindr_cxr
# IMPORTANT: This path must point to the location where you have downloaded
# and extracted the data from PhysioNet, specifically the '1.0.0' directory.
data_dir: "data/physionet.org/files/vindr-cxr/1.0.0"
image_size: 224
batch_size: 32
num_workers: 4

# Focusing on major pathologies as requested
# The dataset has more, but we will filter for these.
# Mapping from original labels to our multiclass problem.
# This assumes we will have a single-column binary indicator for each.
# For a multi-label approach, this would be different.
# Let's start with a multi-class assumption on filtered data.
classes:
  - "Aortic enlargement"
  - "Cardiomegaly"
  - "Pleural effusion"
num_classes: ${to_int:${len:${.classes}}} # OmegaConf resolver to dynamically get the length
